version: '2'

services:
  mysql:
    image: mysql
    container_name: cli-example-database
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
